// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frpipfnajzyepkfpptuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZycGlwZm5hanp5ZXBrZnBwdHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDc3MDAsImV4cCI6MjA2MjYyMzcwMH0.5MA2xS3VRLhMbRpqOmDIMKlnK_LDxtxbefjnvigqeIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);